@echo off
echo Iniciando LMS SanPablo...
echo.

echo Limpiando cache...
if exist .next rmdir /s /q .next 2>nul

echo Verificando dependencias...
npm install --silent

echo Iniciando servidor de desarrollo...
npm run dev 